name: omnisolver-bruteforce-bench
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools<81
  - numpy
  - dimod>=0.12
  - dwave-samplers=1.8.0
  - matplotlib
  - pillow
  - ray-default>=2.9
